### ISSUE TITLE
Arc length parameterization?

### ISSUE THREAD

**Issue by tonnesfn** [ejmahler/SplineLibrary#10]
I am using your spline library to generate splines for moving a robot, and have been using the LoopingCubicHermiteSpline version successfully for a while. I am currently picking points from the spline based on time in a loop, so more or less at even steps in T. What I am experiencing, though, is that the arc length traversed between each step varies a lot (which is to be expected). What would be better for me is some sort of arc length parameterization that would allow me to sample points from the spline based on the arc length, not the internal T value. This would give me constant speed for the robot, given even steps in time.

I was looking at the ArcLength::partition function, and was wondering if that would work? I assume it would if I just gave it the current arc length point (based on time) I want, and throw away all but the first point? Is there a better way to go about this with the current code, or is there an easy addition that could be done to the code to allow this?

**Comment by ejmahler** [comment]
I think you're looking for the "solve length cyclic" method: https://github.com/ejmahler/SplineLibrary/blob/master/spline_library/utils/arclength.h#L78

The "solve length" and "solve length cyclic" methods do the same thing that partition does, but partition does several steps, and the solve length methods do a single step.

For both solve length and solve length cyclic,, you give it a starting point on the spline, and a desired arc length, and it'll return the T value that will give you the desired arc length.
```c++
float startingPoint = 0.25f;
float desiredArcLength = 20.0f;
float endingPoint = ArcLength::solveLength(mySpline, desiredArcLength);

// verify results
float actualArcLength = mySpline.arcLength(startingPoint, endingPoint);

float error = std::abs(actualArcLength - desiredArcLength) / desiredArcLength;
assert(error < 0.001f);
```

The difference is that "solveLength" has no awareness of looping splines, and so you can't give it out of range T values etc, while SolveLengthCyclic handles the looping spline's wrapping logic.

**Comment by ejmahler** [comment]
Another option is to change the `alpha` parameter to the `LoopingCubicHermiteSpline` constructor. Its default is 0. If you set it to another value like 0.5f, it will change the T value of each point so that points with a larger euclidean distance will also have a larger T distance. Any floating point number is valid for `alpha` but I recommend sticking between 0 and 1, and I recommend starting with 0.5

`alpha = 0.5` is also potentially nice for robotics, because it prevents some problems that `alpha=0` has, such as those weird loops: https://i.imgur.com/DaCm3eW.png You probably don't want your robot following that loop!

`alpha` isn't useful if you *need* the T values of the spline to be specific values, but if you're talking about arc length parameterization, there's a chance you don't care about the T values, so it's worth looking into :) Thanks for using SplineLibrary

**Comment by tonnesfn** [comment]
solveLengthCyclic worked perfectly! Thank you very much for the help and the excellent framework.
