### ISSUE TITLE
A question about use the library

### ISSUE THREAD

**Issue by lzcchl** [ejmahler/SplineLibrary#22]
as the example in depository:

/////////////////////////////////////////////////////////////////////////////////////////////
std::vector<QVector2D> splinePoints{
    QVector2D( 0, 0),
    QVector2D( 5, 0),
    QVector2D( 8, 3),
    QVector2D( 6, 1),
};
UniformCRSpline<QVector2D> mySpline(splinePoints);
QVector2D interpolatedPosition = mySpline.getPosition(0.5f);
/////////////////////////////////////////////////////////////////////////////////////////////

I test it, and get the result, the interpolatedPosition is a point between second point "QVector2D( 5, 0)" and third point "QVector2D( 8, 3)", why?
In my mind, the result should be a point between first point "QVector2D( 0, 0)" and second point "QVector2D( 5, 0)", Am I wrong? 
Hope for your reply, thank you.

**Comment by dograt** [comment]
@Izcchl, I struggled with this for a few hours, but if you look at the docs, there is this note on the Catmull-Rom Spline:

> Non-looping version requires an "extra" point on either end of the data set which will not be interpolated

So there you go. Interpolation at a value of 0.5 will be between the second and third points in this case, since [the bounding points aren't part of the generated curve.](https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline)

**Comment by lzcchl** [comment]
thank you very very much.
