### ISSUE TITLE
Where can I find example code?

### ISSUE THREAD

**Issue by mviljamaa** [ejmahler/SplineLibrary#3]
I'm having difficulties in understanding the library.

Specifically,

How can getPosition(floating_t t) be looped over so that the loop goes through "all t"?
Where do I find all t parameters that I must loop over?

Where can I see example code?

**Comment by ejmahler** [comment]
Hello, thanks for posting.

It depends on what you're trying to do. I will post an example that might help, but if I know what you're trying to do I can give a better example.

Let's say you have a looping spline and you want 1000 evenly-spaced points from the spline.

	std::vector<QVector2D> getEvenlySpacedPoints(const Spline<QVector2D, float> &spline, int numPoints) {
		float interval = spline.getMaxT() / numPoints;

		std::vector<QVector2D> result(numPoints);
		for(int i = 0; i < numPoints; i++) {
			float currentT = i * interval;
			result[i] = spline.getPosition(currentT);
		}
		return result;
	}

In this example, we call spline.getMaxT() to find the maximum T value on the spline. For looping splines, the position at maxT will be the same as the position at 0. Then, we divide maxT by the number of points we want. This will be how far apart in T our points will be. Finally, we loop from i = 0 to i = numPoints - 1 and compute the position in the spline at that i.

Does this help? If so, I might add a section for examples to the documentation. If not, what questions do you have?

**Comment by Mviljamaa** [comment]
I'm simply trying to interpolate some sparsely spaced points and I want the interpolation points in [x,y] (at some intervals that give sufficient precision) form so that they can be drawn "connecting the original data points" like in this picture:

http://profmsaeed.org/wp-content/uploads/2011/03/CubicSpline_01.png

**Comment by ejmahler** [comment]
Hi,

Sorry for the delay. I originally had a Vector3D class that you could use in place of QVector2D etc, but it fell out of maintenance because I didn't need it. I've made changes  now to make vector.h more useful.

You can include spline_library/vector.h, the class is Vector<dimension, floating_t>. the default floating_t is float. the dimension is 3d space vs 2d space etc. There are typedefs for common cases: Vector2 for Vector<2, float> and Vector3 for Vector<3, float>

So you could create a std::vector<Vector2> with your data in it, then create a Spline<Vector2> using that std::vector

As for using the same range of X coordinates, you will have to transform the range yourself, to go from 0 to spline.maxT. This should be very easy and fast though.

Finally, if your data is not evenly spaced, your options are somewhat limited. The library theoretically supports it, but you'll have to create your own constructor to support specifying the T value at each point. If you need that, let me know.
